name: CI

on:
  push:
    branches:
    - master
    - bng5-patch-1

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'bng5/website-data'
          submodules: 'true'
      - name: Echo
        run: echo ${{ github.repository }}
      - name: Deploy
        uses: reggionick/s3-deploy@v2
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
