name: CD

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'bng5/website'
          token: ${{ secrets.GH_PAT }}

      - name: Checkout Data
        uses: actions/checkout@v2
        with:
          path: data

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install --only=prod

      - name: Build
        run: npm run build

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
